rrbot:
 rrbot_joint_controller:
  type: "position_controllers/JointTrajectoryController" 
  joints:
   - joint1
   - joint2
  
  gains:
   joint1: {p: 100, i: 0.0, d: 0.1}
   joint2: {p: 100, i: 0.0, d: 0.1}
